version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'unless-stopped'


#  db:
#    image: postgres:13-alpine
#    restart: "unless-stopped"
#    environment:
#      POSTGRES_PASSWORD: password123!